name: "Shayla"
description: "A pretty neato blog"
url: "http://shayla.sawchenko.net"

paginate: 5
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "tables"]
permalink: /blog/:categories/:year/:month/:day/:title/
pygments: true
categories: [web, javascript, java, jekyll, googleglass]
excerpt_separator: "<!-- more -->"
